VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = 'hashicorp/precise32'

    config.vm.provision :ansible do |ansible|
        ansible.groups = {
            "webservers" => ["default"],
            "dev_environment" => ["default"]
        }
        ansible.playbook = 'playbook.yml'
        ansible.extra_vars = { ansible_ssh_user: 'vagrant', vagrant: true }
        ansible.verbose = 'vv'
    end
end
